### PR TITLE
Updated libary to work with the Heroku Cedar stack. Fixes #2

### LINKED ISSUE #2: Compatibly with the new Cedar Stack
Hey there!  I was taking a look at resque, and found this awesome gem, something I was thinking of doing myself.  

A quick question though, is there any plans to have this work with the new [Heroku Cedar Stack](http://devcenter.heroku.com/articles/cedar)? It would be awesome to use this same method to scale different [process models](http://adam.heroku.com/past/2011/5/9/applying_the_unix_process_model_to_web_apps/).

Cheers!

### PR DESCRIPTION
**Pull request by ekosz**
I looked into it myself.  Only a few lines had to be changed.  Tell me what you think.

### CODE REVIEW

**Comment by chrisnicola** [comment]
Any reason this hasn't been looked at?

**Comment by rsenk330** [comment]
This update works for me on the Cedar stack. It would be great if this could be merged in. Maybe for backwards compatibility, there could be another configuration option to set the stack name?

**Comment by chrisnicola** [comment]
Actually are you sure it works?  I tried using @ekosz's branch recently, and it worked for a moment and then wouldn't process another job all of the sudden.  I ended up coding something based on some blog posts I found myself (it isn't a lot of code anyways).

**Comment by ekosz** [comment]
Sorry, the Heroku gem has changed a lot since I created this pull and I haven't worked on it since.  I can take another look if people are interested.

**Comment by rsenk330** [comment]
@lucisferre Yeah, it worked several times for me with no problems. However, I didn't try it with multiple workers.

@ekosz Let me know if you need any help with any testing or development if you look at it some more.

**Comment by chrisnicola** [comment]
I have one worker but multiple jobs. I didn't spend a ton of time debugging into it. It is a hard thing to debug too.

**Comment by masterkain** [comment]
Any news about this?

**Pull request merged**
